# Generated by Django 2.2.9 on 2020-07-02 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('endereco', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('polo', models.CharField(max_length=100)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Sede'), (2, 'UR'), (3, 'ULSAV'), (4, 'EAC'), (5, 'Barreira')])),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.Endereco', verbose_name='fk_endereco')),
                ('subordinado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subpolo', to='usuario.Polo')),
            ],
            options={
                'verbose_name': 'Polo',
                'verbose_name_plural': 'Polos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('setor', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=100)),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Polo', verbose_name='fk_polo')),
                ('subordinado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsetor', to='usuario.Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuario.Setor', verbose_name='fk_setor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['id'],
            },
        ),
    ]
