# Generated by Django 2.2.9 on 2020-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200717_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='sigla',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
