# Generated by Django 2.2.9 on 2020-07-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200717_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['pasta'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterField(
            model_name='setor',
            name='subordinado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsetor', to='usuario.Setor'),
        ),
    ]
