# Generated by Django 2.2.9 on 2022-02-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200717_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='pasta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.Pasta'),
        ),
    ]
